### PR TITLE
replace joda with java time, bump versions

### PR DESCRIPTION
**Pull request by tscholak**
@TugdualSarazin I switched out joda time with java time, and also bumped up the versions of circe and scala.

### CODE REVIEW

**Comment by TugdualSarazin** [comment]
Thank you @tscholak, LGTM

**Comment by tscholak** [comment]
Thanks for merging. It just occurred to me that I forgot to adapt the readme.md. Do you want me to do that?

**Comment by TugdualSarazin** [comment]
Oh I forgot too. Yes, It could be nice if you could do it.

**Comment by tscholak** [comment]
made a PR

**Pull request merged**
